@startuml

autonumber

actor Admin as user

participant ":UI" as ui
participant ":UserController" as controller
participant ":UserService" as service
participant ":LDAPService" as ldap_service
participant ":PostgresUserRepository" as repo
participant ":User" as entity
participant ":Repositories" as repos


activate user
    user -> ui: open user update form

    activate ui
        ui -> user: display user update form
        user --> ui: submit user update data
        ui -> controller: PATCH: /users/{id} with user update data

        activate controller
            controller -> service: update_user(user_data)

            activate service
                service -> ldap_service: exists_with_email(user_data.email)

                activate ldap_service
                    ldap_service --> service: false

                    alt email not registered on ldap
                        ldap_service --> service: true

                        service --> controller: HTTP 400 BAD REQUEST

                        controller --> ui: HTTP 400 BAD REQUEST

                        ui --> user: display error message
                    end alt
                deactivate ldap_service
                service -> repos: _aenter_()

                activate repos
                    repos --> service
                    service -> repo: get_by_id(user_data.id)

                    activate repo
                        repo --> service: User

                    alt user not found
                        repo --> service: None
                        deactivate repo

                        service --> controller: HTTP 400 Bad Request

                        controller --> ui: HTTP 400 Bad Request

                        ui --> user: display error message
                    end alt

                    service -> entity: update(user_data)

                    activate entity
                        entity --> service
                    deactivate entity

                    service -> repo: save(user)

                    activate repo
                        repo --> service
                    deactivate repo

                    service -> repos: commit()
                    service -> repos: _aexit_()

                    repos --> service
                    deactivate repos

                service --> controller: UserResponse
            deactivate service

            controller --> ui: UserResponse
        deactivate controller

        ui --> user: display success message
    deactivate ui
deactivate user
@enduml