@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Admin as user
participant System as sys
activate user
    user -> sys: I want to delete a researcher profile

    activate sys
        sys --> user: presents searchable list of users
        user -> sys: searches and selects user
        sys --> user: presents researcher profile information
        user -> sys: updates information
        sys --> user: asks for confirmation
        user -> sys: confirms
        sys -> sys: saves
        sys --> user: success

        alt error
            sys --> user: error
        end

        deactivate sys
deactivate user

@enduml