@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Admin as user
participant System as sys
activate user
    user -> sys: I want to create a researcher profile

    activate sys
        sys --> user: presents researcher creation formulary
        user -> sys: enters necessary information
        sys -> sys: validates
        sys --> user: success message

        alt error
            sys --> user: error message
        end
    deactivate sys
deactivate user

@enduml